---
apiVersion: v1
kind: Secret
metadata:
  name: opentour-app-1-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/eero-redhat/opentour-app-1-gitops